### ISSUE TITLE
割り算が離散的じゃない

### ISSUE THREAD

**Issue by akakou** [kino-ma/fair_blind_signature#5]
実数に対する割り算が行われているので、離散空間における割り算に変更する。

### 参考

- https://ja.wikipedia.org/wiki/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%A9%E9%80%86%E6%95%B0
- https://qiita.com/drken/items/6b4031ccbb2cab7436f3

**Comment by kino-ma** [comment]
```typescript
    // line 78
    let s: number = Math.floor(b / PI(r_)) % n
```
これでどうでしょうか

**Comment by akakou** [comment]
`b / PI(r_)` が実数になっている気がする。

**Comment by akakou** [comment]
大変参考が悪かったので、貼り直しました。

こういうのをモジュラ逆数と言うらしいです。
（フェルマの小定理ではなく、それをつかったオイラーの定理を貼るべきだった。）

https://ja.wikipedia.org/wiki/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%A9%E9%80%86%E6%95%B0

**Comment by akakou** [comment]
ざっくりいうと、有限な離散空間上の`a / b`というのは、
a * `bの逆元` と言えるわけですよね？

なのでb * `bの逆元` = 1 となる `bの逆元` を探して、
aにかけてあげてください。

**Comment by kino-ma** [comment]
理解した（多分）
ありがとう

**Comment by akakou** [comment]
まあダメそうなら、言ってください！

難易度として、そんなに簡単なことを要求しているつもりではないので、
わからないことがあれば、早めにお願いします！
